#!/bin/bash

quotes=(
  "Push yourself — because no one else is going to do it for you."
  "Debugging: Being the detective in a crime movie where you are also the murderer."
  "You don’t need a new plan, you need to stay consistent with the current one."
  "To understand recursion, you must first understand recursion."
  "Your code doesn’t work? Congratulations, you’re now a software engineer."
  "Dream big, work hard, and remember to commit often."
  "The best time to learn Bash was yesterday. The second best time is now."
  "Calm down and sudo apt-get install patience."
  "A good programmer looks both ways before crossing a one-way street."
  "Stay focused — and may your errors always be meaningful."
  "First, solve the problem. Then, write the code."
  "Code never lies, comments sometimes do."
  "Experience is the name everyone gives to their mistakes."
  "Programs must be written for people to read, and only incidentally for machines to execute."
  "If debugging is the process of removing software bugs, then programming must be the process of putting them in."
  "Before software can be reusable it first has to be usable."
  "Walking on water and developing software from a specification are easy if both are frozen."
  "Measuring programming progress by lines of code is like measuring aircraft building progress by weight."
  "There are two ways to write error-free programs; only the third one works."
  "The most disastrous thing that you can ever learn is your first programming language."
  "Software and cathedrals are much the same — first we build them, then we pray."
  "Don’t worry if it doesn’t work right. If everything did, you’d be out of a job."
  "Talk is cheap. Show me the code."
  "Deleted code is debugged code."
  "If at first you don’t succeed, call it version 1.0."
  "The best thing about a boolean is even if you are wrong, you are only off by a bit."
  "The trouble with programmers is that you can never tell what a programmer is doing until it’s too late."
  "Simplicity is the soul of efficiency."
  "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to produce bigger and better idiots."
  "In theory, there is no difference between theory and practice. But, in practice, there is."
  "Code is like humor. When you have to explain it, it’s bad."
  "Good code is its own best documentation."
  "Programming is like writing a book... except if you miss a single comma on page 126 the whole thing makes no damn sense."
  "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live."
  "The only way to learn a new programming language is by writing programs in it."
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand."
  "Talk is cheap, show me the code."
  "Debugging is twice as hard as writing the code in the first place."
  "Simplicity is prerequisite for reliability."
  "Software testing can be a very effective way to show the presence of bugs, but is hopelessly inadequate for showing their absence."
  "Make it work, make it right, make it fast."
  "One man’s crappy software is another man’s full-time job."
  "If you automate a mess, you get an automated mess."
  "The best method for accelerating a computer is the one that boosts it by 9.8 m/s^2."
  "There is no programming language — no matter how structured — that will prevent programmers from making bad programs."
  "The only thing worse than a bug is a silent bug."
  "Good programmers use their brains, but good guidelines save us having to think out every case."
  "Don’t comment bad code—rewrite it."
  "If you think your users are idiots, only idiots will use it."
  "The function of good software is to make the complex appear to be simple."
  "Always design your program to be easy to change, because it will have to be changed."
  "Code is like a poem; it has to follow some rhythm to be readable."
  "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away."
  "Code is read much more often than it is written."
  "The best error message is the one that never shows up."
  "Good design adds value faster than it adds cost."
  "There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors."
  "Programming can be fun, so can cryptography; however they should not be combined."
  "When to use iterative development? You should use iterative development only on projects that you want to succeed."
  "Software is like entropy: It is difficult to grasp, weighs nothing, and obeys the Second Law of Thermodynamics; i.e., it always increases."
  "A language that doesn’t affect the way you think about programming is not worth knowing."
  "Programs are meant to be read by humans and only incidentally for computers to execute."
  "There’s no place like 127.0.0.1."
  "If you want to make an easy job seem mighty hard, just keep putting off doing it."
  "Measuring programming progress by lines of code is like measuring aircraft building progress by weight."
  "You can’t have great software without a great team, and most software teams behave like dysfunctional families."
  "Programming is the art of telling another human what one wants the computer to do."
  "Beware of programmers who carry screwdrivers."
  "The most important property of a program is whether it accomplishes the intention of its user."
  "To iterate is human, to recurse divine."
  "It always takes longer than you expect, even when you take into account Hofstadter’s Law."
  "Good code is its own best documentation."
  "Programming is not easy like Sunday morning."
  "The best programs are written so that computing machines can perform them quickly and so that human beings can understand them clearly."
  "Computers are good at following instructions, but not at reading your mind."
  "Don’t write better error messages, write code that doesn’t need them."
  "Premature optimization is the root of all evil."
  "If you want to build a ship, don’t drum up people to collect wood and assign tasks, but rather teach them to long for the endless immensity of the sea."
  "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code."
  "Code never lies, comments sometimes do."
  "A good programmer is someone who looks both ways before crossing a one-way street."
  "Programming is like sex. One mistake and you have to support it for the rest of your life."
  "The best way to get a project done faster is to start sooner."
  "When debugging, novices insert corrective code; experts remove defective code."
  "Programming languages, like pizzas, come in only two sizes: too big and too small."
  "Walking on water and developing software from a specification are easy if both are frozen."
  "The computer was born to solve problems that did not exist before."
  "An infinite loop is like a bad relationship — eventually you gotta break out."
  "Real programmers don’t comment their code. If it was hard to write, it should be hard to understand."
  "If it compiles, ship it."
  "Better to have 100 functions operate on one data structure than 10 functions on 10 data structures."
  "The function of good software is to make the complex appear to be simple."
  "Sometimes the best code is no code at all."
  "Code is like humor: when you have to explain it, it’s bad."
  "The first 90 percent of the code accounts for the first 90 percent of the development time."
  "The remaining 10 percent of the code accounts for the other 90 percent of the development time."
)

while true; do
  clear
  random_index=$((RANDOM % ${#quotes[@]}))
  echo
  echo "Quote of the moment:"
  echo
  echo "\"${quotes[$random_index]}\""
  echo
  sleep 5
done
